version: '3.9'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      ENV: dev
      PORT: 8080
      API_KEY: fee263fe-9eae-48f4-8e2f-23dd77c7cde2
      ADMIN_API_KEY: 8312c08f-2c0b-41b7-8fea-54fc7a907a30
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - redis
    volumes:
      - .:/opt/app/api
  redis:
    image: redis:7.0.5-alpine
    restart: 'always'
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local